'use strict';
// Single source of truth for the featured-card model lists: reads the two tool registries and
// writes docs/cards-data.js (window.TOOL_BRANDS + window.WEBPATCHER_BRANDS). Run on any model
// change (or via a githook). The profile page never hand-maintains these lists.
//
//   TOOL_BRANDS       <- lb-tool-web/manufacturers/registry.js   (models[].tested, kind)
//   WEBPATCHER_BRANDS <- lb-webpatcher/manufacturers/registry.js (experimental flag)
//
// Run: node scripts/gen-cards.js   (needs the sibling lb-tool-web + lb-webpatcher repos)

const fs = require('fs');
const path = require('path');

var TOOL_REG = path.resolve(__dirname, '../../lb-tool-web/manufacturers/registry.js');
var WEB_REG = path.resolve(__dirname, '../../lb-webpatcher/manufacturers/registry.js');
var OUT = path.resolve(__dirname, '../docs/cards-data.js');

// Load a registry.js in isolation (it assigns window.REGISTRY) and return that array.
function loadRegistry(file) {
  var g = { window: {} };
  var code = fs.readFileSync(file, 'utf8');
  new Function('window', code).call(g, g.window);   // registry.js sets window.REGISTRY
  return g.window.REGISTRY || [];
}

// lb-tool-web: one entry per manufacturer, models[] carry a `tested` flag; kind 'static' = info page.
function toolBrands(reg) {
  return reg.map(function (m) {
    var brand = (m.brand && m.brand.title) || m.name;
    // Some labels repeat the brand ("NIU KQi 300X", "IO HAWK Elite X 2.0"); the card shows the brand
    // in bold already, so strip a leading brand prefix to avoid doubling it.
    var re = new RegExp('^' + brand.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\s+', 'i');
    var lab = function (x) { return x.label.replace(re, ''); };
    var models = m.models || [];
    var tested = models.filter(function (x) { return x.tested; }).map(lab);
    var untested = models.filter(function (x) { return !x.tested; }).map(lab);
    var o = { name: brand };
    o.models = tested;
    if (untested.length) o.untested = untested;
    if (m.kind === 'static') o.info = true;
    return o;
  });
}

// lb-webpatcher: one entry per model; experimental = untested. Group by manufacturer, keep first-seen order.
function webpatcherBrands(reg) {
  var order = [], byBrand = {};
  reg.forEach(function (m) {
    var b = (m.brand && m.brand.title) || m.name;
    if (!byBrand[b]) { byBrand[b] = { name: b, models: [], untested: [] }; order.push(b); }
    (m.experimental ? byBrand[b].untested : byBrand[b].models).push(m.name);
  });
  return order.map(function (b) {
    var o = { name: byBrand[b].name, models: byBrand[b].models };
    if (byBrand[b].untested.length) o.untested = byBrand[b].untested;
    return o;
  });
}

var tool = toolBrands(loadRegistry(TOOL_REG));
var web = webpatcherBrands(loadRegistry(WEB_REG));

var out = "'use strict';\n"
  + '// GENERATED by scripts/gen-cards.js from the tool registries - do not edit by hand.\n'
  + '// TOOL_BRANDS <- lb-tool-web registry; WEBPATCHER_BRANDS <- lb-webpatcher registry.\n'
  + 'window.TOOL_BRANDS = ' + JSON.stringify(tool, null, 2) + ';\n'
  + 'window.WEBPATCHER_BRANDS = ' + JSON.stringify(web, null, 2) + ';\n';

fs.writeFileSync(OUT, out);
console.log('wrote', path.relative(process.cwd(), OUT));
console.log('  TOOL_BRANDS:', tool.map(function (b) { return b.name + '(' + b.models.length + '/' + ((b.untested || []).length) + ')'; }).join(' '));
console.log('  WEBPATCHER_BRANDS:', web.map(function (b) { return b.name + '(' + b.models.length + '/' + ((b.untested || []).length) + ')'; }).join(' '));
